-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Packages.Knit.Services.PadService.RF.UpgradePad
Event:InvokeServer(
    "-1"
)