-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.UpdateSpeedUI
firesignal(Event.OnClientEvent, 
    {
        ["5"] = 740071876819,
        ["1"] = 126150028247,
        ["10"] = 1827480264281
    },
    202,
    false,
    false
)